# Generated by Django 4.2.1 on 2023-05-11 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
